//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace MazikCare.MobEval.RoutingServiceAX {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CustomDetailXmlField;
        
        private System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.FaultMessageList> FaultMessageListArrayField;
        
        private System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.InfologMessage> InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.FaultMessageList> FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.InfologMessage> InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.FaultMessage> FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.FaultMessage> FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MazikCare.MobEval.RoutingServiceAX.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MazikCare.MobEval.RoutingServiceAX.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HMSalesLineServiceContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class HMSalesLineServiceContract : MazikCare.MobEval.RoutingServiceAX.XppObjectBase {
        
        private string parmDescriptionField;
        
        private string parmRecIdField;
        
        private string parmSalesIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmDescription {
            get {
                return this.parmDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.parmDescriptionField, value) != true)) {
                    this.parmDescriptionField = value;
                    this.RaisePropertyChanged("parmDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmRecId {
            get {
                return this.parmRecIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parmRecIdField, value) != true)) {
                    this.parmRecIdField = value;
                    this.RaisePropertyChanged("parmRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSalesId {
            get {
                return this.parmSalesIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSalesIdField, value) != true)) {
                    this.parmSalesIdField = value;
                    this.RaisePropertyChanged("parmSalesId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.HMPatientDataContracts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.HMSalesLineServiceContract))]
    public partial class XppObjectBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HMPatientDataContracts", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class HMPatientDataContracts : MazikCare.MobEval.RoutingServiceAX.XppObjectBase {
        
        private string chiefcompField;
        
        private string parmAddressField;
        
        private string parmAgeField;
        
        private string parmContactField;
        
        private string parmGenderField;
        
        private string parmMRNField;
        
        private string parmNameField;
        
        private long parmRecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string chiefcomp {
            get {
                return this.chiefcompField;
            }
            set {
                if ((object.ReferenceEquals(this.chiefcompField, value) != true)) {
                    this.chiefcompField = value;
                    this.RaisePropertyChanged("chiefcomp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmAddress {
            get {
                return this.parmAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.parmAddressField, value) != true)) {
                    this.parmAddressField = value;
                    this.RaisePropertyChanged("parmAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmAge {
            get {
                return this.parmAgeField;
            }
            set {
                if ((object.ReferenceEquals(this.parmAgeField, value) != true)) {
                    this.parmAgeField = value;
                    this.RaisePropertyChanged("parmAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmContact {
            get {
                return this.parmContactField;
            }
            set {
                if ((object.ReferenceEquals(this.parmContactField, value) != true)) {
                    this.parmContactField = value;
                    this.RaisePropertyChanged("parmContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmGender {
            get {
                return this.parmGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.parmGenderField, value) != true)) {
                    this.parmGenderField = value;
                    this.RaisePropertyChanged("parmGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmMRN {
            get {
                return this.parmMRNField;
            }
            set {
                if ((object.ReferenceEquals(this.parmMRNField, value) != true)) {
                    this.parmMRNField = value;
                    this.RaisePropertyChanged("parmMRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmName {
            get {
                return this.parmNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmNameField, value) != true)) {
                    this.parmNameField = value;
                    this.RaisePropertyChanged("parmName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmRecId {
            get {
                return this.parmRecIdField;
            }
            set {
                if ((this.parmRecIdField.Equals(value) != true)) {
                    this.parmRecIdField = value;
                    this.RaisePropertyChanged("parmRecId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/netfx/2009/05/routing", ConfigurationName="RoutingServiceAX.IRequestReplyRouter")]
    public interface IRequestReplyRouter {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestReplyRouterChannel : MazikCare.MobEval.RoutingServiceAX.IRequestReplyRouter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestReplyRouterClient : System.ServiceModel.ClientBase<MazikCare.MobEval.RoutingServiceAX.IRequestReplyRouter>, MazikCare.MobEval.RoutingServiceAX.IRequestReplyRouter {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RequestReplyRouterClient() : 
                base(RequestReplyRouterClient.GetDefaultBinding(), RequestReplyRouterClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.reqReplyEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(EndpointConfiguration endpointConfiguration) : 
                base(RequestReplyRouterClient.GetBindingForEndpoint(endpointConfiguration), RequestReplyRouterClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RequestReplyRouterClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RequestReplyRouterClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.reqReplyEndpoint)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.reqReplyEndpoint)) {
                return new System.ServiceModel.EndpointAddress("http://ax2012-a.contoso.com:85/MicrosoftDynamicsAXAif60/MZKWEB/xppservice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return RequestReplyRouterClient.GetBindingForEndpoint(EndpointConfiguration.reqReplyEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return RequestReplyRouterClient.GetEndpointAddress(EndpointConfiguration.reqReplyEndpoint);
        }
        
        public enum EndpointConfiguration {
            
            reqReplyEndpoint,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="RoutingServiceAX.MazikCareWebService")]
    public interface MazikCareWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/getSalesOrderNo", ReplyAction="http://tempuri.org/MazikCareWebService/getSalesOrderNoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/getSalesOrderNoAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoResponse> getSalesOrderNoAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/postPackingSlip", ReplyAction="http://tempuri.org/MazikCareWebService/postPackingSlipResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/postPackingSlipAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipResponse> postPackingSlipAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/getSalesLines", ReplyAction="http://tempuri.org/MazikCareWebService/getSalesLinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/getSalesLinesAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesResponse> getSalesLinesAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/getPatientImage", ReplyAction="http://tempuri.org/MazikCareWebService/getPatientImageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/getPatientImageAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageResponse> getPatientImageAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/getAllPropects", ReplyAction="http://tempuri.org/MazikCareWebService/getAllPropectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/getAllPropectsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsResponse> getAllPropectsAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/getAllPatients", ReplyAction="http://tempuri.org/MazikCareWebService/getAllPatientsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/getAllPatientsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsResponse> getAllPatientsAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/createPrescription", ReplyAction="http://tempuri.org/MazikCareWebService/createPrescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/createPrescriptionAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionResponse> createPrescriptionAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/createNewPrescription", ReplyAction="http://tempuri.org/MazikCareWebService/createNewPrescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/createNewPrescriptionAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionResponse> createNewPrescriptionAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/convertProspectToPatient", ReplyAction="http://tempuri.org/MazikCareWebService/convertProspectToPatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/convertProspectToPatientAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientResponse> convertProspectToPatientAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/addNewSONotesDocument", ReplyAction="http://tempuri.org/MazikCareWebService/addNewSONotesDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/addNewSONotesDocumentAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentResponse> addNewSONotesDocumentAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazikCareWebService/addNewDocument", ReplyAction="http://tempuri.org/MazikCareWebService/addNewDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MazikCare.MobEval.RoutingServiceAX.AifFault), Action="http://tempuri.org/MazikCareWebService/addNewDocumentAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentResponse> addNewDocumentAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetSalesOrderNoRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetSalesOrderNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encounterRecId;
        
        public MazikCareWebServiceGetSalesOrderNoRequest() {
        }
        
        public MazikCareWebServiceGetSalesOrderNoRequest(string _encounterRecId) {
            this._encounterRecId = _encounterRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetSalesOrderNoResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetSalesOrderNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServiceGetSalesOrderNoResponse() {
        }
        
        public MazikCareWebServiceGetSalesOrderNoResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServicePostPackingSlipRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServicePostPackingSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encounterRecId;
        
        public MazikCareWebServicePostPackingSlipRequest() {
        }
        
        public MazikCareWebServicePostPackingSlipRequest(string _encounterRecId) {
            this._encounterRecId = _encounterRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServicePostPackingSlipResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServicePostPackingSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServicePostPackingSlipResponse() {
        }
        
        public MazikCareWebServicePostPackingSlipResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetSalesLinesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetSalesLinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _salesId;
        
        public MazikCareWebServiceGetSalesLinesRequest() {
        }
        
        public MazikCareWebServiceGetSalesLinesRequest(string _salesId) {
            this._salesId = _salesId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetSalesLinesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetSalesLinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.HMSalesLineServiceContract> response;
        
        public MazikCareWebServiceGetSalesLinesResponse() {
        }
        
        public MazikCareWebServiceGetSalesLinesResponse(System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.HMSalesLineServiceContract> response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetPatientImageRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetPatientImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string patientRecId;
        
        public MazikCareWebServiceGetPatientImageRequest() {
        }
        
        public MazikCareWebServiceGetPatientImageRequest(string patientRecId) {
            this.patientRecId = patientRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetPatientImageResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetPatientImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public byte[] response;
        
        public MazikCareWebServiceGetPatientImageResponse() {
        }
        
        public MazikCareWebServiceGetPatientImageResponse(byte[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetAllPropectsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetAllPropectsRequest {
        
        public MazikCareWebServiceGetAllPropectsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetAllPropectsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetAllPropectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.HMPatientDataContracts> response;
        
        public MazikCareWebServiceGetAllPropectsResponse() {
        }
        
        public MazikCareWebServiceGetAllPropectsResponse(System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.HMPatientDataContracts> response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetAllPatientsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetAllPatientsRequest {
        
        public MazikCareWebServiceGetAllPatientsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceGetAllPatientsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceGetAllPatientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.HMPatientDataContracts> response;
        
        public MazikCareWebServiceGetAllPatientsResponse() {
        }
        
        public MazikCareWebServiceGetAllPatientsResponse(System.Collections.ObjectModel.ObservableCollection<MazikCare.MobEval.RoutingServiceAX.HMPatientDataContracts> response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceCreatePrescriptionRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceCreatePrescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string patientRecId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string clinicstaffRecId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string lengthofneed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public System.Collections.ObjectModel.ObservableCollection<string> itemForOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<string> diagnosis;
        
        public MazikCareWebServiceCreatePrescriptionRequest() {
        }
        
        public MazikCareWebServiceCreatePrescriptionRequest(string patientRecId, string clinicstaffRecId, string lengthofneed, System.Collections.ObjectModel.ObservableCollection<string> itemForOrder, System.Collections.ObjectModel.ObservableCollection<string> diagnosis) {
            this.patientRecId = patientRecId;
            this.clinicstaffRecId = clinicstaffRecId;
            this.lengthofneed = lengthofneed;
            this.itemForOrder = itemForOrder;
            this.diagnosis = diagnosis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceCreatePrescriptionResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceCreatePrescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServiceCreatePrescriptionResponse() {
        }
        
        public MazikCareWebServiceCreatePrescriptionResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceCreateNewPrescriptionRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceCreateNewPrescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string patientRecId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string clinicstaffRecId;
        
        public MazikCareWebServiceCreateNewPrescriptionRequest() {
        }
        
        public MazikCareWebServiceCreateNewPrescriptionRequest(string patientRecId, string clinicstaffRecId) {
            this.patientRecId = patientRecId;
            this.clinicstaffRecId = clinicstaffRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceCreateNewPrescriptionResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceCreateNewPrescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServiceCreateNewPrescriptionResponse() {
        }
        
        public MazikCareWebServiceCreateNewPrescriptionResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceConvertProspectToPatientRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceConvertProspectToPatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _prospectRecId;
        
        public MazikCareWebServiceConvertProspectToPatientRequest() {
        }
        
        public MazikCareWebServiceConvertProspectToPatientRequest(string _prospectRecId) {
            this._prospectRecId = _prospectRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceConvertProspectToPatientResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceConvertProspectToPatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServiceConvertProspectToPatientResponse() {
        }
        
        public MazikCareWebServiceConvertProspectToPatientResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceAddNewSONotesDocumentRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceAddNewSONotesDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encounterRecId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public byte[] byteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string fileExt;
        
        public MazikCareWebServiceAddNewSONotesDocumentRequest() {
        }
        
        public MazikCareWebServiceAddNewSONotesDocumentRequest(string _encounterRecId, byte[] byteArray, string fileName, string fileExt) {
            this._encounterRecId = _encounterRecId;
            this.byteArray = byteArray;
            this.fileName = fileName;
            this.fileExt = fileExt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceAddNewSONotesDocumentResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceAddNewSONotesDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServiceAddNewSONotesDocumentResponse() {
        }
        
        public MazikCareWebServiceAddNewSONotesDocumentResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceAddNewDocumentRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceAddNewDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encounterRecId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public byte[] byteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string fileExt;
        
        public MazikCareWebServiceAddNewDocumentRequest() {
        }
        
        public MazikCareWebServiceAddNewDocumentRequest(string _encounterRecId, byte[] byteArray, string fileName, string fileExt) {
            this._encounterRecId = _encounterRecId;
            this.byteArray = byteArray;
            this.fileName = fileName;
            this.fileExt = fileExt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MazikCareWebServiceAddNewDocumentResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MazikCareWebServiceAddNewDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public MazikCareWebServiceAddNewDocumentResponse() {
        }
        
        public MazikCareWebServiceAddNewDocumentResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MazikCareWebServiceChannel : MazikCare.MobEval.RoutingServiceAX.MazikCareWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MazikCareWebServiceClient : System.ServiceModel.ClientBase<MazikCare.MobEval.RoutingServiceAX.MazikCareWebService>, MazikCare.MobEval.RoutingServiceAX.MazikCareWebService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MazikCareWebServiceClient() : 
                base(MazikCareWebServiceClient.GetDefaultBinding(), MazikCareWebServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_MazikCareWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MazikCareWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MazikCareWebServiceClient.GetBindingForEndpoint(endpointConfiguration), MazikCareWebServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MazikCareWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MazikCareWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MazikCareWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MazikCareWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MazikCareWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.getSalesOrderNoAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoRequest request) {
            return base.Channel.getSalesOrderNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoResponse> getSalesOrderNoAsync(string _encounterRecId) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesOrderNoRequest();
            inValue._encounterRecId = _encounterRecId;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).getSalesOrderNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.postPackingSlipAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipRequest request) {
            return base.Channel.postPackingSlipAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipResponse> postPackingSlipAsync(string _encounterRecId) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServicePostPackingSlipRequest();
            inValue._encounterRecId = _encounterRecId;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).postPackingSlipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.getSalesLinesAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesRequest request) {
            return base.Channel.getSalesLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesResponse> getSalesLinesAsync(string _salesId) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetSalesLinesRequest();
            inValue._salesId = _salesId;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).getSalesLinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.getPatientImageAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageRequest request) {
            return base.Channel.getPatientImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageResponse> getPatientImageAsync(string patientRecId) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetPatientImageRequest();
            inValue.patientRecId = patientRecId;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).getPatientImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.getAllPropectsAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsRequest request) {
            return base.Channel.getAllPropectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsResponse> getAllPropectsAsync() {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPropectsRequest();
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).getAllPropectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.getAllPatientsAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsRequest request) {
            return base.Channel.getAllPatientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsResponse> getAllPatientsAsync() {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceGetAllPatientsRequest();
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).getAllPatientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.createPrescriptionAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionRequest request) {
            return base.Channel.createPrescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionResponse> createPrescriptionAsync(string patientRecId, string clinicstaffRecId, string lengthofneed, System.Collections.ObjectModel.ObservableCollection<string> itemForOrder, System.Collections.ObjectModel.ObservableCollection<string> diagnosis) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreatePrescriptionRequest();
            inValue.patientRecId = patientRecId;
            inValue.clinicstaffRecId = clinicstaffRecId;
            inValue.lengthofneed = lengthofneed;
            inValue.itemForOrder = itemForOrder;
            inValue.diagnosis = diagnosis;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).createPrescriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.createNewPrescriptionAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionRequest request) {
            return base.Channel.createNewPrescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionResponse> createNewPrescriptionAsync(string patientRecId, string clinicstaffRecId) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceCreateNewPrescriptionRequest();
            inValue.patientRecId = patientRecId;
            inValue.clinicstaffRecId = clinicstaffRecId;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).createNewPrescriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.convertProspectToPatientAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientRequest request) {
            return base.Channel.convertProspectToPatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientResponse> convertProspectToPatientAsync(string _prospectRecId) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceConvertProspectToPatientRequest();
            inValue._prospectRecId = _prospectRecId;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).convertProspectToPatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.addNewSONotesDocumentAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentRequest request) {
            return base.Channel.addNewSONotesDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentResponse> addNewSONotesDocumentAsync(string _encounterRecId, byte[] byteArray, string fileName, string fileExt) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewSONotesDocumentRequest();
            inValue._encounterRecId = _encounterRecId;
            inValue.byteArray = byteArray;
            inValue.fileName = fileName;
            inValue.fileExt = fileExt;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).addNewSONotesDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentResponse> MazikCare.MobEval.RoutingServiceAX.MazikCareWebService.addNewDocumentAsync(MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentRequest request) {
            return base.Channel.addNewDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentResponse> addNewDocumentAsync(string _encounterRecId, byte[] byteArray, string fileName, string fileExt) {
            MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentRequest inValue = new MazikCare.MobEval.RoutingServiceAX.MazikCareWebServiceAddNewDocumentRequest();
            inValue._encounterRecId = _encounterRecId;
            inValue.byteArray = byteArray;
            inValue.fileName = fileName;
            inValue.fileExt = fileExt;
            return ((MazikCare.MobEval.RoutingServiceAX.MazikCareWebService)(this)).addNewDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_MazikCareWebService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_MazikCareWebService)) {
                return new System.ServiceModel.EndpointAddress("http://ax2012-a.contoso.com:85/MicrosoftDynamicsAXAif60/MZKWEB/xppservice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return MazikCareWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_MazikCareWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return MazikCareWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_MazikCareWebService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_MazikCareWebService,
        }
    }
}
